services:
  mongo:
    image: mongo
    restart: always
    ports:
      - $MONGO_PORT:$MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
